name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Lint code
        # We expect warnings in the example files, but no errors
        run: npm run lint -- --max-warnings 50
        continue-on-error: false
        
      - name: Failure message
        if: ${{ failure() }}
        run: |
          echo "CI build failed. Please check the logs for more information."
          echo "Common issues:"
          echo "- ESLint configuration errors"
          echo "- Test failures"