name: Claude Autofix

on:
  issues:
    types: [opened, labeled]

jobs:
  claude-autofix:
    if: ${{ github.event.label.name == 'claude-fix' || contains(github.event.issue.labels.*.name, 'claude-fix') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Git user
        run: |
          git config --global user.name "Claude Autofix"
          git config --global user.email "noreply@anthropic.com"

      - name: Create branch for fix
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH_NAME="fix/claude-autofix-issue-${ISSUE_NUMBER}"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Prepare issue content for Claude
        run: |
          # Extract issue details safely to separate files
          echo "${{ github.event.issue.title }}" > issue_title.txt
          echo "${{ github.event.issue.body }}" > issue_body.txt
          
          # Create prompt file with issue details using safer file-based approach
          cat > claude_prompt.txt << 'EOF'
          I need you to fix the following issue in the eslint-plugin-vibe-check repository:
          
          # Issue: 
          EOF
          
          # Append title and body from files instead of directly
          cat issue_title.txt >> claude_prompt.txt
          echo "" >> claude_prompt.txt
          echo "" >> claude_prompt.txt
          cat issue_body.txt >> claude_prompt.txt
          
          # Add additional instructions
          cat >> claude_prompt.txt << 'EOF'
          
          Please analyze the code, make necessary changes, run tests to verify your solution, and prepare a concise PR description.
          EOF
          
          echo "Prompt file created for Claude."

      - name: Run Claude Code in non-interactive mode
        id: claude_code
        timeout-minutes: 15
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          # Install Anthropic CLI tool
          npm install -g @anthropic-ai/claude-code
          
          # Create a script to safely handle the Claude prompt
          cat > run_claude.sh << 'EOF'
          #!/bin/bash
          set -euo pipefail
          
          # Add timeout to ensure Claude doesn't run indefinitely (10 minutes)
          timeout 600s bash -c '
          # Run Claude Code with the prompt in non-interactive mode
          # -p (--print): Run query and exit immediately
          # --verbose: Show detailed logging
          # --allowedTools: Specify permitted tools to use
          CLAUDE_OUTPUT=$(cat claude_prompt.txt | claude -p --verbose \
            --allowedTools "Bash(git diff:*)" "Bash(git log:*)" "Bash(npm:*)" "Edit" "Read" "Glob" "Grep" \
            --json)
          
          # Extract PR description from Claude's output
          # Handle potentially malformed JSON with error handling
          echo "$CLAUDE_OUTPUT" > claude_raw_output.txt
          if echo "$CLAUDE_OUTPUT" | jq -e . >/dev/null 2>&1; then
            # Valid JSON - use jq to extract
            echo "$CLAUDE_OUTPUT" | jq -r ".response" | grep -A 10 "PR Description:" > pr_description.txt || true
          else
            # Invalid JSON - fall back to grep directly
            echo "Warning: Invalid JSON output from Claude. Trying direct pattern matching."
            grep -A 10 "PR Description:" claude_raw_output.txt > pr_description.txt || true
          fi
          
          # Ensure we have at least some content for the PR description
          if [ ! -s pr_description.txt ]; then
            echo "## PR Description" > pr_description.txt
            echo "This fix was automatically generated by Claude Code." >> pr_description.txt
          fi
          '
          
          # Check if timeout occurred
          if [ $? -eq 124 ]; then
            echo "Claude Code execution timed out after 10 minutes."
            exit 1
          fi
          
          # We've made sure pr_description.txt exists with a fallback,
          # so no need to check it here anymore
          
          echo "Claude Code completed successfully."
          exit 0
          EOF
          
          # Make the script executable
          chmod +x run_claude.sh
          
          # Run the script with progress indicator
          echo "Starting Claude Code execution (this may take several minutes)..."
          ./run_claude.sh
          
          # Check if Claude was able to make changes
          if [ $? -ne 0 ]; then
            echo "Claude Code could not fix the issue. Exiting."
            exit 1
          fi

      - name: Run tests to validate changes
        id: run_tests
        run: |
          npm test
          if [ $? -ne 0 ]; then
            echo "Tests failed. Not proceeding with PR creation."
            exit 1
          fi
          echo "Tests passed successfully."

      - name: Lint code
        id: run_lint
        run: |
          npm run lint -- --max-warnings 50 --ignore-pattern "examples/*" --ignore-pattern "lib/rules/never-assume.js" --ignore-pattern "tmp.js"
          if [ $? -ne 0 ]; then
            echo "Linting failed. Not proceeding with PR creation."
            exit 1
          fi
          echo "Linting passed successfully."

      - name: Commit changes
        run: |
          git add .
          git commit -m "fix: Auto-fix issue #${{ github.event.issue.number }} using Claude Code
          
          🤖 Generated with Claude Code
          
          Co-Authored-By: Claude <noreply@anthropic.com>" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: Auto-fix issue #${{ github.event.issue.number }} using Claude Code"
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: false
          title: "fix: Auto-fix issue #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          body-file: pr_description.txt
          labels: "claude-autofix"
          base: "main"

      - name: Comment on issue
        if: steps.create_pr.outputs.pull-request-number
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi there! This issue has been automatically addressed by Claude Code.
            
            A pull request has been created at #${{ steps.create_pr.outputs.pull-request-number }} with the proposed fix.
            
            Please review the changes and provide feedback or merge the PR if it resolves the issue.
            
            🤖 This was generated automatically by the Claude Autofix workflow.

      - name: Handle failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Unfortunately, Claude was unable to automatically fix this issue. The GitHub Action ran into an error.
            
            You may need to manually address this issue, or refine the issue description and try again.
            
            🤖 This was generated automatically by the Claude Autofix workflow.